### PR TITLE
Some additions

### PR DESCRIPTION
**Pull request by camilokawerin**
I've added the support for the 'Side Bar' menu and the command 'status'.

### CODE REVIEW

**Comment by ses4j** [comment]
First of all, thank you for the pull request!  I'm definitely interested in adding the Sidebar commands and happy to add Status, though I don't really use the Sidebar myself (I just CTRL-P my way to any given file.)

I ran into some issues that may need to be addressed before I can merge it in:
- There are some print statements in `tgit_commands.py` there which threw errors, maybe because you're testing with ST2/Python 2.x and I'm on Python 3?  Anyway, those ought to be removed.
- Many menu commands had `...` following them, indicating that choosing the item pops up another window.  I don't think they should be removed.  To illustrate, you can see this in ST itself, for `Open Containing Folder...`: 
  
  image
- Why did you remove the `Commit (repo)...` command?  That's the one I find most useful of all.

**Comment by camilokawerin** [comment]
Hi!

> There are some print statements in tgit_commands.py there which threw errors, maybe because you're testing with ST2/Python 2.x and I'm on Python 3? Anyway, those ought to be removed.

I forgot to remove them before to commit. Now they are gone.

**Comment by camilokawerin** [comment]
> Many menu commands had ... following them, indicating that choosing the item pops up another window. I don't think they should be removed. To illustrate, you can see this in ST itself, for Open Containing Folder...:

Just some obsessive attention on brevity. Added again.

**Comment by camilokawerin** [comment]
> Why did you remove the Commit (repo)... command? That's the one I find most useful of all.

Because I've moved all command relative to repositories to the Side Bar menu, but you're right: it's useful to have it in the context menu too.

**Comment by camilokawerin** [comment]
Thanks for your comments! I hope these changes help.

**Comment by ses4j** [comment]
@camilokawerin Hi - I haven't forgotten about this, I'm using your branch daily to give it a full spin.  Also thinking about whether I want to tweak my workflow to use more sidebar.

**Comment by ses4j** [comment]
@camilokawerin I brought the PR into the (prerelease) v1.1 branch, and rearranged and renamed a little bit to conform with TortoiseGit a little.  Feel free to argue.. ;)

**Pull request merged**
